tasks:
  - name: API console
    init: cd api && go get
    command: go run .
  - name: GUI console
    init: cd gui && npm install
    command: REACT_APP_API_URL=`gp url 8080` npm start

ports:
  - name: GUI
    description: React frontend to interact with the API
    port: 3000
    onOpen: open-browser
    visibility: private
  - name: Backend
    description: API
    port: 8080
    onOpen: ignore
    visibility: private
